module.exports = {
  "Display4Text":         require("./Display4Text"),
  "Display3Text":         require("./Display3Text"),
  "Display2Text":         require("./Display2Text"),
  "Display1Text":         require("./Display1Text"),
  "HeadlineText":         require("./HeadlineText"),
  "SubheadlineText":      require("./SubheadlineText"),
  "TitleText":            require("./TitleText"),
  "Body2Text":            require("./Body2Text"),
  "Body1Text":            require("./Body1Text"),
  "ButtonText":           require("./ButtonText"),
  "MenuText":             require("./MenuText"),
  "ListItemText":         require("./ListItemText"),
  "CaptionText":          require("./CaptionText"),
  "GridTileTitleText":    require("./GridTileTitleText"),
  "GridTileSubtitleText": require("./GridTileSubtitleText"),
  "GridTileBodyText":     require("./GridTileBodyText"),
  "GridTileBoldBodyText": require("./GridTileBoldBodyText"),
};
